### ISSUE TITLE
What version of Opensll does this use?

### ISSUE THREAD

**Issue by bmulcahy** [Southern/node-x509#21]
I may have missed it somewhere but just wanted to verify which version this uses. Also does openssl need to be installed(runnable from command line)?

**Comment by Southern** [comment]
You do have to install it locally for the headers to be available for
compiling. No specific version is required.

**Comment by Southern** [comment]
You don't have to have a specific version. You will need to have OpenSSL installed if you are on a Windows system. Otherwise, compilation uses the OpenSSL headers that are provided as a dependency of Node.

You can find the different compilation conditions [in lines 22-51](https://github.com/Southern/node-x509/blob/master/binding.gyp#L22-L51) of the `binding.gyp` file.

**Comment by yorkie** [comment]
This seems to be answered by @Southern, closing :)
