### ISSUE TITLE
Does not work for DER encoded certificates

### ISSUE THREAD

**Issue by weagle08** [Southern/node-x509#27]
It would be nice if this worked on DER (PKCS7) encoded certificates, and if that get's added in, might as well throw in PKCS12 as well. I wouldn't mind implementing if someone could show me a good way to differentiate in code. I don't see a friendly way to do this in the openssl library. Or should the node x509 library just try all three if passed a cert and return on the one that does not exception out (not a fan of using exceptions as a program flow)?

**Comment by Southern** [comment]
For the sake of this module, let's stick X509 only. If you wanted to implement this in a fork, however, I would suggest implementing both `PEM_read_bio_PKCS7` (found [here](https://www.openssl.org/docs/manmaster/crypto/pem.html)) and `d2i_X509_bio` (found [here](https://www.openssl.org/docs/manmaster/crypto/d2i_X509.html)). You can use these exactly how the other PEM functions are being called in the current code. OpenSSL should return NULL immediately if there is a problem with the encoding that you're trying to use in a specific function.

For example: if you were trying to pass in raw DER format to `PEM_read_bio_X509`, `PEM_read_bio_X509` should return NULL faster than we could differentiate between the encodings in our code. It immediately checks to see if the "PEM" data has the header required for PEM data. If not, it will add an error to the error stack and return NULL.

If you were to add this, I would say to implement all of the `PEM_read_bio_*` functions first. Those, like I mentioned above, will return NULL immediately if the a valid PEM header isn't found. That will allow you to catch any PEM data before you run into `d2i_X509_bio`.

Let me know if you implement this as a fork. We can always add your fork into the README so that anyone looking for this functionality will have the option to use it.
