### ISSUE TITLE
Support Node v5.4.0

### ISSUE THREAD

**Issue by cpetrov** [Southern/node-x509#29]
Node v5.4.0 fails to create hashes after parsing a certificate.

**package.json:**
```javascript
{
  "main": "server.js",
  "dependencies": {
    "x509": "^0.2.3"
  }
}
```
**server.js:**
```javascript
var x509 = require("x509");
var crypto = require("crypto");
// x509.parseCert("certificate.cer");
var hash = crypto.createHash("md5");
console.log(hash.digest("hex"));
```

Uncomment the line and the following error will be thrown:
```
crypto.js:50
  this._handle = new binding.Hash(algorithm);
                 ^

Error: error:0906D06C:PEM routines:PEM_read_bio:no start line
    at Error (native)
    at new Hash (crypto.js:50:18)
    at Object.Hash (crypto.js:49:12)
    at Object.<anonymous> (/home/christian/Documents/sandbox/server.js:4:19)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:430:10)
    at startup (node.js:141:18)
```

**Comment by Southern** [comment]
The error message that you received is from OpenSSL. "No start line" typically means that there was no starting line to indicate what the file is. For example, a certificate should start with "-----BEGIN CERTIFICATE-----" and end with "-----END CERTIFICATE-----". This is required for all certificates to show the beginning and end of the certificate since multiple certificates can be defined in one file.

**Comment by Southern** [comment]
The error message that you received is from OpenSSL. "No start line" typically means that there was no starting line to indicate what the file is. For example, a certificate should start with `-----BEGIN CERTIFICATE-----` and end with `-----END CERTIFICATE-----`. This is required for all certificates to show the beginning and end of the certificate since multiple certificates can be defined in one file.

**Comment by Southern** [comment]
No response in two weeks. Closing this.
