### ISSUE TITLE
Remove read from file fallback

### ISSUE THREAD

**Issue by Enteee** [Southern/node-x509#34]
I'm using the parser with user submitted input 
```javascript
const cert = x509.parseCert(userInput)
```
currently a user could read an arbitrary file from file system using the x509 parser and I've no chance to tell the parser not to do so. This is why I'd suggest removing the fallback read-from-fs. If this functionality is needed,  one can still use the parser as as described in the readme:
```javascript
const fs = require('fs'),
      x509 = require('x509');
var issuer = x509.getIssuer(fs.readFileSync('./certs/your.crt').toString());
```

**Comment by yorkie** [comment]
See https://github.com/Southern/node-x509/blob/master/src/x509.cc#L123, you are able to make your example work, because when `PEM_read_bio_X509` with certification data fails, x509 will convert to use filename.

Closing this issue for now, _if still a problem here, feel free to reopen it_, thanks @Enteee

**Comment by Enteee** [comment]
I think you did not understand what I mean:
> currently a user could read an arbitrary file from file system using the x509 parser and I've no chance to tell the parser **NOT** to do so. This is why I'd suggest removing the fallback read-from-fs.

@yorkie : Tell me if you need more information

**Comment by Enteee** [comment]
@yorkie I can not reopen the issue, can you please do this for me?

**Comment by Southern** [comment]
@Enteee This is not an issue with this module. You should _never_ allow direct user input into _anything_. This module would be the least of your worries because it will throw an error immediately once it recognizes that the file that the user is trying to access is not a valid PEM file: https://github.com/Southern/node-x509/blob/master/src/x509.cc#L131-L138

As it stands, this isn't an issue.

**Comment by Enteee** [comment]
@Southern I'm aware that I'm not supposed to use user input without validation, but when It comes down to parsing this is always a chicken-egg problem: How can I validate user input without parsing it <-> how can I parse user input without validating? This is critical when the parser is powerful (or even turing complete). So this is why I'd keep the parser as slim as possible. Or at least make this additional functionality opt-in (**not** opt-out!).  In node-x509 not even opt-out is possible. Don't make the XML-mistake.
```javascript
const cert = x509.parseCertFromFileSync(userInput)
```

Anyway, back to the main issue: validating without parsing; I am currently checking for the '-----BEGIN CERTIFICATE-----' & '-----END CERTIFICATE-----' - armor but this is a valid filename as well: unlikely but valid ;) The same holds for the base64 encoded certificate. Moste filenames are valid base64 encoded messages. So how am I supposed to validate the user input?

**Comment by Rush** [comment]
I do agree this is a security issue. Never allowing direct user input is one thing and ambiguity is another. Imagine only XML validator and what would happen if XML parsing function was reading files from disk if the input doesn't validate? This situation is the same. 

Another problem is separation of concerns, why should x509 library be reading any files? Node.js is much better and safer in reading files. 

@Enteee if performance is not your primary requirement but security is, I do advise using my spin off project from node-x509 -  https://github.com/encharm/x509.js. It's C++ compiled to 100% JS via emscripten.  Performance is 50% of node-x509 but the upside is there is no reading of files and no native code.

**Comment by Southern** [comment]
@Rush It is only a "security issue" for those who allow direct user input, which should never happen in any case. OpenSSL provides the ability to read the file directly into a BIO and then parse that BIO. That is why we are not depending on Node to read the file and convert the file into a string before then sending it to X509 for parsing. It is also why we allow the user to decide whether they would like it to be read via the BIO by sending us a filename, or you can send in the entire file after reading it with Node.

I appreciate you taking the time to create your fork a while back, but I do not appreciate you using this issue as an advertisement. I repeat, this _IS NOT_ an issue with this module... security or otherwise.

**Comment by Enteee** [comment]
> Imagine only XML validator and what would happen if XML parsing function was reading files from disk if the input doesn't validate?

@Rush see https://en.wikipedia.org/wiki/XML_external_entity_attack
@Southern This is not my use case but: If I wanted to write a certificate viewer, how I'd do this without "allowing direct user input"? Or in general what kind of use-case do you have in mind which does not require "direct user input"?

**Comment by yorkie** [comment]
I do agree 100% with @Southern's point, though this library is a Node.js package, it's even a bridge to OpenSSL, so we should keep consistent with the common usage of that community, using Node.js file system might be something hacky.

> currently a user could read an arbitrary file from file system using the x509 parser and I've no chance to tell the parser NOT to do so. This is why I'd suggest removing the fallback read-from-fs.

@Southern for @Enteee's problem, how about adding an option to avoid creating `BIO_s_file` object, and throw an invalid certification data?

**Comment by Southern** [comment]
@Enteee You would have to use Node to read in the file and then send that file to the X509 module as a string if you don't trust that X509 will prevent directory traversal, etc.

@yorkie It's already going to throw an error once it gets to https://github.com/Southern/node-x509/blob/master/src/x509.cc#L131-L138 and it doesn't return the contents of the file with the error. Seems like a moot point to add in another error for something that's already being handled.

**Comment by yorkie** [comment]
Oh wait, I find a memory leak when we calling `Nan::ThrowError` like https://github.com/Southern/node-x509/blob/master/src/x509.cc#L135, because the method has been returned without calling `BIO_free` on created `bio` object, @Southern is it a leak, if yes, I will create a Pull Request for this :-)

**Comment by Rush** [comment]
> I appreciate you taking the time to create your fork a while back, but I do not appreciate you using this issue as an advertisement.

I apologize if you took an offence and I will refrain from doing so in the future. Since both projects are non-commercial I thought we should act towards addressing users' needs.

@Southern If you don't agree with the security argument, perhaps ambiguity argument could convince you. Reading code `x509.parseCert(string)` does not give any indication that file will be read.  If the code read `x509.parseFromStringOrFile(string)` then it would be clear and hence secure - nobody would be tempted to pass user submitted data. Of course easiest route is to remove any file reading functionality. How modern code is written is after all:
```js
fs.readFileAsync(filename).then(x509.parseCert);
```
Now, if `x509.parseCert` is doing any file reading .. it's doing it synchronously and blocks the event loop. What if the file is on a network file system? Then it can block for a long time.

**Comment by Enteee** [comment]
@Southern What I'm doing: 
1. Getting the certificate as string from the user. 
2. Validate the string by checking if there is a '-----BEGIN CERTIFICATE-----' & '-----END CERTIFICATE-----' - armor
3. Calling x509 with the said string.

I do think this kind of validation is not sufficient so what I'll going to change this to is:
1. Get the string from the user
2. Validate the string
3. Write the string to file
4. x509.parseCert(filename)

This means I've to have a writable file system, something I probably won't have in my final deployment. But as a dirty hack this should work for now.

**Comment by Southern** [comment]
@Rush I didn't take offense to you wanting people to use your module. I took offense to derailing the issue with a module that we are already advertising in our README, solely based on us saying that this is not an issue in the module.

It says in the README that `cert` can either be a filename or a string. It's been there forever.

> Notes:
> 
> `cert` may be a filename or a raw base64 encoded PEM string in any of these methods.

I don't see any ambiguity there. It clearly states what is expected and the same information is available on NPM.

@yorkie Good catch. We should `BIO_free` before throwing the error. I'd greatly appreciate it if you could take care of that, bump the version, and publish it to NPM. Going to be busy for the next few days.

@Enteee If you're validating that the user input is a valid PEM by checking that it has the `-----BEGIN CERTIFICATE-----` and `-----END CERTIFICATE-----`, how is this an issue to begin with? The user input will be handled as a string and there will be no file reading at all.

**Comment by Rush** [comment]
> don't see any ambiguity there. It clearly states what is expected and the same information is available on NPM.

Having a documentation does not make the code more readable. Best code is obvious what it does from code alone.

Also, I don't really get what you defend this reading file fallback approach. What's the actual use case to justify this behavior? Usually one wants to do one or the either.

**Comment by Southern** [comment]
@Rush It has been documented since the very beginning of this module, and it is obvious what it is doing in the lines of code that I posted earlier. It's not causing a problem other than misunderstandings that could be addressed by simply reading the documentation that has provided. Many companies are and have been using it in production with no problem or misunderstanding about how this module works.

Better question: what's the reason to NOT allow behavior that is commonly used in the OpenSSL community?

**Comment by Rush** [comment]
> Better question: what's the reason to NOT allow behavior that is commonly used in the OpenSSL community?

OpenSSL is not to be trusted. Best to minimize its usage to bare minimum. The less usage, the less opportunity for future security issues. If you give OpenSSL opportunity to access filesystem, you expose the filesystem to OpenSSL bugs.

> Many companies are and have been using it in production with no problem or misunderstanding about how this module works.

And I congratulate you on this. However most companies simply use node modules without much thinking. And this is a good thing. Simple interfaces allow for this. They wanna parse a cert and your module does the job. How many of them actually expect the code to read a file though? I know I didn't until I started reading the code of this module. If I see `x509.parseCert` and an example that shows usage through `fs.readFileSync` reading documentation is the last thing I do. I wish well for this module but if you wanna keep it as it is, it's your prerogative.

**Comment by Southern** [comment]
@Rush I agree that OpenSSL shouldn't be trusted with everything, especially in light of the recent OpenSSL fuck ups that surfaced. Even though you and I believe that it shouldn't be trusted, our opinions cannot prevent the end user from having their own opinion and choosing what they would like to use.

> How many of them actually expect the code to read a file though?

Everyone should know about it if they took the time to read the documentation instead of blindly using a module that they know nothing about, which is more of a security risk than reading in a file with OpenSSL.

**Comment by Enteee** [comment]
This conversation is starting to drift. Anyway I agree with @Rush:
> Also, I don't really get what you defend this reading file fallback approach. What's the actual use case to justify this behavior? Usually one wants to do one or the either.

From my personal experience: Keep your parser as simple as possible. I repeat myself, don't make the XML mistake.

> Better question: what's the reason to NOT allow behavior that is commonly used in the OpenSSL community?

You keep repeating yourself but I don't understand this. The openssl x509-command has:
>  -in filename
>     This specifies the input filename to read a certificate from or standard input if this option is not specified.

Which means, in contrast to your module, the 'read from stdin'-functionality is opt-in. There is no such thing as: "If the stdin string is no valid pem try to read from a file instead"

**Comment by Southern** [comment]
I keep repeating myself because it doesn't seem to be understood that this is to allow the end user the option of reading with OpenSSL or Node. The X509 command line indeed has `-in`. Where do you think the file is being read from in that case? That is why this is an option in the module, and I'm done with this semantic holy war of something that is not and will not be an issue now or in the near future. Don't allow direct user input without serialization. That's the answer to your issue. This is now closed.

**Comment by Enteee** [comment]
amen.
