### ISSUE TITLE
Interpreting a certificate as a string poses security risk

### ISSUE THREAD

**Issue by RubenVerborgh** [Southern/node-x509#51]
The methods in this library are currently implemented as follows:

1. Try to interpret the string argument as certificate data.
2. If this fails, then interpret it as a path.

There are no explicit methods that only accept raw data or a file.

As such, one needs to always apply a safety check before passing certificate data from a third party, since x509 might interpret it as a path and read a sensitive certificate file. A maliciously crafted "certificate" (that is actually a path) could therefore have unintended side effects.

The solution is to have a flag that prohibits interpretation as a path, or to change the method signatures altogether.

**Comment by Southern** [comment]
This has previously been covered in another issue, #34. The security of this package is solely up to the end-user and what they determine is best for them.

By the way, you should never get any output for a file path that any user inputs unless it's a valid PEM file. Check out [src/x509.cc#L209-L225](https://github.com/Southern/node-x509/blob/master/src/x509.cc#L209-L225). You can see that this module tries OpenSSL's `PEM_read_bio_X509` on any file that it loads from this fallback functionality. You get nothing more than an error back from this module when that call fails. Therefore any attempts to read a file that isn't a valid PEM formatted X509 file is going to result in an error from OpenSSL saying something like the beginning or ending header isn't found, the content isn't in the PEM format or an X509 certificate, etc.

Closing this, but feel free to leave any feedback/questions that you may have.

**Comment by RubenVerborgh** [comment]
Thanks, @Southern. While I agree with

> you should never get any output for a file path that any user inputs unless it's a valid PEM file

That still leaves the case where the path _does_ point to a valid PEM file.

> Check out [src/x509.cc#L209-L225](https://github.com/Southern/node-x509/blob/master/src/x509.cc#L209-L225).

That's what I did, and <q>If raw read fails, try reading the input as a filename</q> is exactly what I consider a security issue. Concrete case in point: at MIT, we're building an HTTP server with certificate-based authentication. I had to specifically [check](https://github.com/solid/node-solid-server/blob/180a11434cbb07657216df5c930b60defd518fca/lib/api/authn/webid-tls.js#L61-L65) and [test](https://github.com/solid/node-solid-server/blob/180a11434cbb07657216df5c930b60defd518fca/test/integration/acl-tls.js#L1038-L1047) whether the client was not trying to send a server-owned certificate by using a file path.

I cannot think of _any_ case where the fallback from string to path is used _for the sake of that functionality_. I.e., implementers highly likely only use it because there are no different methods available for the separate functionalities. For a library that performs a security-related task (certificates), such a fallback with potential security consequences seems highly undesired. In fact, I suspect that several dependents of x509 with the "pass me the certificate as a string" option will be susceptible to reading local, trusted certificates instead.

So I would only agree with

> The security of this package is solely up to the end user

if x509 had to bring _extra_ security measures to the table to support existing functionality. Yet in this case, the fallback mechanism is probably not even desired functionality, but only the convenience of a single method name. Unfortunately, this convenience cannot be turned off, and comes with a security issue.

**Comment by Southern** [comment]
The reason it's like this isn't because of convenience. It has been this
way since the beginning and there has been no valid reason to change it
other than people wanting us to add more security so they don't have to.
You agreed with "the security of this module is solely based on the end
user" and have already implemented your own security. If you limit the
input to only be a certificate string, you will never hit the fallback. On
the flip side, you could also limit the input to only be file paths of
certificates stored locally. It's up to you, as the end user, to decide how
you want it to function by limiting your users' input into the module. It
should be that way regardless of whether we add more security into this
module or not.


From: Ruben Verborgh <notifications@github.com> <notifications@github.com>
Reply: Southern/node-x509
<reply@reply.github.com>
<reply@reply.github.com>
Date: July 16, 2017 at 2:01:08 PM
To: Southern/node-x509 <node-x509@noreply.github.com>
<node-x509@noreply.github.com>
Cc: Colton Baker <educability@gmail.com> <educability@gmail.com>, Mention
<mention@noreply.github.com> <mention@noreply.github.com>
Subject:  Re: [Southern/node-x509] Interpreting a certificate as a string
poses security risk (#51)

Thanks, @Southern <https://github.com/southern>. While I agree with

you should never get any output for a file path that any user inputs unless
it's a valid PEM file

That still leaves the case where the path *does* point to a valid PEM file.

Check out src/x509.cc#L209-L225
<https://github.com/Southern/node-x509/blob/master/src/x509.cc#L209-L225>.

That's what I did, and If raw read fails, try reading the input as a
filename is exactly what I consider a security issue. Concrete case in
point: at MIT, we're building an HTTP server with certificate-based
authentication. I had to specifically check
<https://github.com/solid/node-solid-server/blob/180a11434cbb07657216df5c930b60defd518fca/lib/api/authn/webid-tls.js#L61-L65>
and test
<https://github.com/solid/node-solid-server/blob/180a11434cbb07657216df5c930b60defd518fca/test/integration/acl-tls.js#L1038-L1047>
whether the client was not trying to send a server-owned certificate by
using a file path.

I cannot think of *any* case where the fallback from string to path is
used *for
the sake of that functionality*. I.e., implementers highly likely only use
it because there are no different methods available for the separate
functionalities. For a library that performs a security-related task
(certificates), such a fallback with potential security consequences seems
highly undesired. In fact, I suspect that several dependents of x509 with
the "pass me the certificate as a string" option will be susceptible to
reading local, trusted certificates instead.

So I would only agree with

The security of this package is solely up to the end user

if x509 had to bring *extra* security measures to the table to support
existing functionality. Yet in this case, the fallback mechanism is
probably not even desired functionality, but only the convenience of a
single method name. Unfortunately, this convenience cannot be turned off,
and comes with a security issue.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/Southern/node-x509/issues/51#issuecomment-315625876>,
or mute the thread

**Comment by RubenVerborgh** [comment]
> It has been this way since the beginning

Not a valid argument as to whether it is right or wrong: literally all software libraries have bugs that were there since the beginning 😉 

> people wanting us to add more security so they don't have to

Or because they don't know how to?
Or because they are unsure they capture all corner cases?
Or because it is safer to implement security once and reuse?

> have already implemented your own security

I have, others likely have not, and I have no decisive evidence as to whether I have implemented the security correctly such that it will never attempt to read a file. (Weird things might happen with null characters or other things.)

> If you limit the input to only be a certificate string, you will never hit the fallback.

I'm just checking for BEGIN/END CERTIFICATE with base64-encoded in between. Can still be an invalid certificate string, and hit the fallback. Only way to know for sure that it's a valid certificate string, is to implement (part of) an X509 library myself; kind of defeats the purpose.

> On the flip side, you could also limit the input to only be file paths of certificates stored locally.

That is still possible if the interfaces for files and raw input are separated.

> It's up to you, as the end user, to decide how you want it to function by limiting your users' input into the module. It should be that way

I agree it should be that way; that's exactly why it makes more sense to have different method names for raw input and filename input. Then you can explicitly make the decision based on the kind of input you have, rather than trying to pre-process the input yourself, likely failing in covering all cases, and hoping that the fallback will not be hit (which you cannot guarantee unless you parse the certificate yourself).

**Comment by Southern** [comment]
So you would rather us be responsible for maintaining the security of your platform instead? That's what I'm getting from this conversation and I refuse to open that can of worms. I will not be responsible for someone's security failing due to a bug, edge case, or anything else. That will remain the responsibility of the end user, period.

I honestly find it hard to believe that no one has brought up any issues with this functionality other than "I want it to work this way instead because I had to implement my own security." This module has been published for 4+ years and gets between 7,000 and 20,000 downloads per month. I feel like we would have known about this being an issue before now if it were truly a flaw or vulnerability, and we also would not have Fortune 500s using this module in their platforms if they didn't feel safe.

**Comment by RubenVerborgh** [comment]
Happy to discuss, but we're not going to get far if we don't follow a sound argumentation.
My points were:

1. **This library has a security issue (and I provided a demonstration as proof).**
2. **That issue should be fixed in this library (and I provided argumentation).**

(Un-)fortunately, none of my two points are refuted by your points above:

- **So you would rather us be responsible for maintaining the security of your platform instead?**
  - No, I just don't want a non-file path to be potentially interpreted as a file path, as this is unsafe, and _I cannot prevent this from happening with x509_ (without reimplementing the certificate logic myself, which defeats the purpose of using x509). The prevention part is crucial here.
- **I will not be responsible for someone's security failing due to a bug**
  1. You are not, because the MIT license on your code explicitly avoids that.
  2. Because of the unsafe fallback, you are actually more likely to be the cause of someone's security failing.
  3. It's not because you fix one bug, or prevent a bug from happening by removing an unsafe mechanism, that you are accountable for all others (especially not given the license).
- **I honestly find it hard to believe that no one has brought up any issues with this functionality**
  - Neither your belief nor anyone's bringing up of issues proves my points 1 or 2 wrong.
- **“I want it to work this way instead because I had to implement my own security.”**
  - That's not what I said (and this type of argumentation is known as “straw man argument”). I said that it is impossible to guarantee the fallback will not be triggered without validating the certificate first (which would invalidate the use of x509).
- **This module has been published for 4+ years and gets between 7,000 and 20,000 downloads per month.**
   - Congrats, but that's not a criterion for not having bugs, so it does not invalidate my two points above. If intended as a contest, I have a module with more than a million monthly downloads. If intended as a proof of failure-safety, I'll point to Node.js as a counterexample, which has millions of monthly downloads yet an important security flaw was discovered last week.
- **we also would not have Fortune 500s using this module in their platforms if they didn't feel safe**
  - Feeling safe is not the same as being safe; and in security, it's a well-known saying that you're better off knowingly unsafe than assumingly safe.
  - Also, several Fortune 500s use Node.js, feel safe, but there still was a critical bug last week.
  - Furthermore, I found and demonstrated the security issue, so it exists. Try pointing the Fortune 500s to this thread and see what they think, I'd be happy to be proven wrong (with a sound argumentation).

Now that this is out of the way, can we focus on arguments that counter any of my two main points?

**Comment by Southern** [comment]
I haven't seen any proof of any security flaw. All I've seen is someone whining about having to sanitize their users' input into a 3rd party module, as should be done anyway so that any security regressions in this module would be caught and handled by your own security. Why should we implement security when you should be doing it in the first place to avoid such issues with regressions and other unforeseen circumstances?

Only you and one other person have complained about this in the 4+ years that this module has been in existence. Neither of you have been able to argue the case with a valid reason other than wanting foolproof security OOTB. You agree that users should be responsible for the security of their platforms when using this module but then argue that we should be responsible for fixing something that isn't broke in the first place due to a "security flaw" that you've yet to prove exists? That's absurd.

My download numbers weren't to boast about the downloads this module receives, although you apparently think this is a pissing contest. It was meant to point out that there are more people using this than just yourself. Out of those thousands of people that have used it, only two of you think this is a big enough issue to start an argument about it. It's not fair to those other users to change a function, that they've been using for over 4 years now, just because you want it to work your way.

Yes, the fallback is automatic. Yes, the fallback could be hit if you do not limit your users' input. No, it is not my problem that someone may not know how to secure their platform against directory traversal or any other file path attack. That is the job of you, the end user, to educate yourself in order to prevent such attacks. You are correct that, legally at least, I cannot be held responsible. Unfortunately, I would still feel responsible for such a catastrophic event if my module were involved even though I cannot be held legally responsible. It seems that you would be just fine with ignoring all of your users as long as your opinion is suited because you provided them with an MIT license.

I have been down this road before and I will not go down it again. You are literally whining about having to implement your own security while nitpicking everything that I say, rather than proving that an actual security flaw exists in this module. You want to nitpick me posting the download statistics for this module when I haven't said one word about you pulling the "I went to or am going to MIT, so I'm better than you" routine until now. What other reason would you have to mention MIT than to try to intimidate others with your superiority complex? I am done with this conversation. You can thank your petty and childish attitude for my disregard to any further commentary that you have regarding this "security flaw". Let me know when you have some real proof and then maybe we'll continue this conversation. A 3 line change and a test proves nothing to me other than you were completely capable of implementing your own security with minimal coding required on your part.

**Comment by RubenVerborgh** [comment]
> All I've seen is someone whining about having to sanitize their users' input into a 3rd party module

Straw man argument. As explained above, the problem is that the only foolproof way to sanitize is to perform the X509 parsing yourself, voiding the need to use x509.

> Why should we implement security when you should be doing it in the first place

Because implementing that security in a foolproof way requires implementing the part of functionality we try to use the x509 library for in the first place.

> Neither of you have been able to argue the case with a valid reason

I keep on mentioning the reason but you keep on arguing other things.

**Let me help you prove me wrong by splitting my argument into steps:**

1. If a raw certificate string is passed, and it is invalid, it is interpreted as a path.
2. Interpreting a non-path as a path has security consequences: a server's private certificate might be read.
3. The only way to avoid the path interpretation is to verify the certificate is valid.
4. In order to verify the validity of the certificate, one basically has to implement an X509 library, which defeats the point of using this x509 library.
5. The problem can be avoided by splitting the methods into raw string and file methods.
6. You can even do 5 in a backwards-compatible way, by just adding new methods (xxxxRaw and xxxxFromFile) instead of replacing the current method.

**In order to prove me wrong, please disprove at least one of the above points.**
Happy to respond to any argument that does so. (Less happy to be put words in my mouth I didn't say.)

**Comment by Southern** [comment]
I will be waiting for proof in another issue with a valid point. I don’t have time to argue semantics, theories, etc.
